language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -q
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "firefox --version"
  - bin/flake8 setup.py
  - bin/flake8 collective
  - bin/test -vvv --all
